name = Pisces
description = A 2 column layout with a prominent hero region.
preview = preview.png
template = pisces-layout

; Regions
regions[branding]       = Branding
regions[header1]        = Header 1
regions[header2]        = Header 2
regions[header3]        = Header 3
regions[navigation]     = Navigation bar
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[preface]        = Preface
regions[content]        = Content
regions[sidebar]        = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/pisces/pisces.layout.css
stylesheets[all][] = css/layouts/pisces/pisces.layout.no-query.css
