<?php

/**
 * Revert cod_bof feature to set the correct pathauto variable event OG label.
 */
function cod_bof_update_7002() {
  $revert = array(
    'cod_bof' => array('variable', 'field_instance'),
  );
  features_revert($revert);

  return array();
}

/**
 * Revert cod_bof feature to set the correct views filter for the bof schedule.
 */
function cod_bof_update_7003() {
  $revert = array(
    'cod_bof' => array('views_view'),
  );
  features_revert($revert);

  return array();
}
